apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dbp98utar-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:f4c86fbaec2abea07b2cc31a197c33607f4db3aa@sha256:7ec91f3c1ae8a2980bcf458beb6a803d543b8f9e61c205619a4bbb11df8805dc
          name: container-image
